package com.prreviewer.model;

import jakarta.persistence.*;

/**
 * Represents a single inline comment generated by the AI.
 */
@Entity
@Table(name = "comments")
public class Comment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "review_id", nullable = false)
    private Review review;

    @Column(nullable = false)
    private String file;

    @Column(nullable = false)
    private Integer line;

    @Column(nullable = false)
    private String severity;

    @Column(nullable = false)
    private String category;

    @Column(columnDefinition = "TEXT", nullable = false)
    private String message;

    // ---- Constructors ----

    public Comment() {}

    private Comment(Builder builder) {
        this.review   = builder.review;
        this.file     = builder.file;
        this.line     = builder.line;
        this.severity = builder.severity;
        this.category = builder.category;
        this.message  = builder.message;
    }

    // ---- Getters & Setters ----

    public Long getId()               { return id; }
    public Review getReview()         { return review; }
    public void setReview(Review v)   { this.review = v; }
    public String getFile()           { return file; }
    public void setFile(String v)     { this.file = v; }
    public Integer getLine()          { return line; }
    public void setLine(Integer v)    { this.line = v; }
    public String getSeverity()       { return severity; }
    public void setSeverity(String v) { this.severity = v; }
    public String getCategory()       { return category; }
    public void setCategory(String v) { this.category = v; }
    public String getMessage()        { return message; }
    public void setMessage(String v)  { this.message = v; }

    // ---- Builder ----

    public static Builder builder() { return new Builder(); }

    public static final class Builder {
        private Review review;
        private String file, severity, category, message;
        private Integer line;
        public Builder review(Review v)    { this.review   = v; return this; }
        public Builder file(String v)      { this.file     = v; return this; }
        public Builder line(Integer v)     { this.line     = v; return this; }
        public Builder severity(String v)  { this.severity = v; return this; }
        public Builder category(String v)  { this.category = v; return this; }
        public Builder message(String v)   { this.message  = v; return this; }
        public Comment build()             { return new Comment(this); }
    }
}
